### ISSUE TITLE
Package manager cog

### ISSUE THREAD

**Issue by HexadecimalPython** [Thessia/Liara#8]
An updater which updates the bot depending on which cogs you have loaded.
Also if you have any factory modules deleted it will ignore them.

**Comment by Pandentia** [comment]
I agree with this, however factory modules should never be deleted. Deleting any kind of modules that come with the bot is generally a bad idea, and should be discouraged at any cost.

**Comment by HexadecimalPython** [comment]
Update 1/19/17:
None of us has started work on it yet.
This is due to us wanting to stabilize Liara first then work on other things.
and laziness.

**Comment by Pandentia** [comment]
I've started work on `Pacman`, which will hopefully be a *lot* of fun to make packages and mirrors for. (I'll admit, the name inspiration came from Arch Linux's package manager.)

**Comment by Pandentia** [comment]
:tada: 44c9b03

I'm gonna go get some shut-eye now.
